# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
array2 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([[
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]],
    [[11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]]])

(array1.shape, array1.ndim), (array2.shape, array2.ndim), (array3.shape, array3.ndim)

(((5,), 1), ((2, 5), 2), ((2, 2, 5), 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(f"Shape: {array1.shape} \nNumber of Dimension: {array1.ndim} \nData Types: {array1.dtype} \nSize: {array1.size} \nType: {type(array1)}")

Shape: (5,) 
Number of Dimension: 1 
Data Types: int64 
Size: 5 
Type: <class 'numpy.ndarray'>


In [10]:
# Attributes of 2-dimensional array
print(f"Shape: {array2.shape} \nNumber of Dimension: {array2.ndim} \nData Types: {array2.dtype} \nSize: {array2.size} \nType: {type(array2)}")

Shape: (2, 5) 
Number of Dimension: 2 
Data Types: int64 
Size: 10 
Type: <class 'numpy.ndarray'>


In [11]:
# Attributes of 3-dimensional array
print(f"Shape: {array3.shape} \nNumber of Dimension: {array3.ndim} \nData Types: {array3.dtype} \nSize: {array3.size} \nType: {type(array3)}")

Shape: (2, 2, 5) 
Number of Dimension: 3 
Data Types: int64 
Size: 20 
Type: <class 'numpy.ndarray'>


In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(array2)
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [18]:
df2 = pd.DataFrame(array3.reshape((5, 4)))
df2

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [19]:
array3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [21]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2), dtype=np.int8)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [22]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3), dtype=np.int8)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int8)

In [23]:
# Create an array within a range of 0 and 100 with step 3
a_range = np.arange(0, 100, 3)
a_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(0, 10, size=(7, 2))
random_arr

array([[9, 9],
       [3, 3],
       [1, 5],
       [8, 3],
       [9, 5],
       [9, 5],
       [8, 2]])

In [25]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_arr2 = np.random.random((3, 5))
random_arr2

array([[0.6923108 , 0.67603601, 0.90639899, 0.09381175, 0.66745054],
       [0.60124098, 0.29513285, 0.03719007, 0.9508036 , 0.99561747],
       [0.8239852 , 0.61462035, 0.84994319, 0.62913003, 0.7299007 ]])

In [27]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr3 = np.random.randint(0, 10, size=(4, 6))
random_arr3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens? Nothing Happened

Are the numbers in the array different or the same? Why do think this is?

Numbers in the array are the same, because we have seed to 42 above the cell

In [29]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_arr4 = np.random.randint(1, 10, size=(3, 7))
random_arr4

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]])

In [ ]:
# Find the unique numbers in the array you just created
np.unique(random_arr4)

array([1, 2, 3, 4, 5, 7, 9])

In [30]:
# Find the 0'th index of the latest array you created
random_arr4[0]

array([7, 8, 3, 1, 4, 2, 8])

In [32]:
# Get the first 2 rows of latest array you created
random_arr4[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr4[:2, :2]

array([[7, 8],
       [4, 2]])

In [34]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr5 = np.random.randint(0, 10, size=(3, 5))
ones_arr1 = np.ones((3, 5))

random_arr5, ones_arr1

(array([[1, 4, 7, 9, 8],
        [8, 0, 8, 6, 8],
        [7, 0, 7, 7, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [35]:
# Add the two arrays together
random_arr5 + ones_arr1

array([[ 2.,  5.,  8., 10.,  9.],
       [ 9.,  1.,  9.,  7.,  9.],
       [ 8.,  1.,  8.,  8.,  3.]])

In [37]:
# Create another array of ones of shape (5, 3)
ones_arr2 = np.ones((5, 3))
ones_arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# Try add the array of ones and the other most recent array together
random_arr5 + ones_arr2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is? It produced an error because the shape of the arrays we are 

trying to perform arithmetic on is not aligned.

How would you fix it? The fix I will explore will be to use Transpose

In [39]:
random_arr5.shape, ones_arr2.shape

((3, 5), (5, 3))

In [40]:
# Create another array of ones of shape (3, 5)
ones_arr3 = np.ones((3, 5))
ones_arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
# Subtract the new array of ones from the other most recent array
random_arr5 - ones_arr3

array([[ 0.,  3.,  6.,  8.,  7.],
       [ 7., -1.,  7.,  5.,  7.],
       [ 6., -1.,  6.,  6.,  1.]])

In [43]:
# Multiply the ones array with the latest array
random_arr5 * ones_arr3

array([[1., 4., 7., 9., 8.],
       [8., 0., 8., 6., 8.],
       [7., 0., 7., 7., 2.]])

In [45]:
random_arr5

array([[1, 4, 7, 9, 8],
       [8, 0, 8, 6, 8],
       [7, 0, 7, 7, 2]])

In [44]:
# Take the latest array to the power of 2 using '**'
random_arr5 ** 2

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]])

In [47]:
# Do the same thing with np.square()
np.square(random_arr5)

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]])

In [48]:
# Find the mean of the latest array using np.mean()
np.mean(random_arr5)

np.float64(5.466666666666667)

In [49]:
# Find the maximum of the latest array using np.max()
np.max(random_arr5)

np.int64(9)

In [50]:
# Find the minimum of the latest array using np.min()
np.min(random_arr5)

np.int64(0)

In [51]:
# Find the standard deviation of the latest array
np.std(random_arr5)

np.float64(3.0739045022396008)

In [52]:
# Find the variance of the latest array
np.var(random_arr5)

np.float64(9.448888888888888)

In [57]:
# Reshape the latest array to (3, 5, 1)
reshape_array = np.reshape(random_arr5, (3, 5, 1))
reshape_array

array([[[1],
        [4],
        [7],
        [9],
        [8]],

       [[8],
        [0],
        [8],
        [6],
        [8]],

       [[7],
        [0],
        [7],
        [7],
        [2]]])

In [58]:
reshape_array[0], reshape_array[1], reshape_array[2]

(array([[1],
        [4],
        [7],
        [9],
        [8]]),
 array([[8],
        [0],
        [8],
        [6],
        [8]]),
 array([[7],
        [0],
        [7],
        [7],
        [2]]))

In [59]:
# Transpose the latest array
t_array = reshape_array.T
t_array

array([[[1, 8, 7],
        [4, 0, 0],
        [7, 8, 7],
        [9, 6, 7],
        [8, 8, 2]]])

In [61]:
t_array.ndim, t_array.shape

(3, (1, 5, 3))

What does the transpose do? It switches the axes

In [62]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_int1 = np.random.randint(0, 10, (3, 2))
rand_int2 = np.random.randint(0, 10, (3, 3))

rand_int1, rand_int2

(array([[0, 7],
        [2, 2],
        [0, 4]]),
 array([[9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]))

In [63]:
# Perform a dot product on the two newest arrays you created
rand_int2.dot(rand_int1)

array([[ 12, 111],
       [ 12, 100],
       [  2,  51]])

In [66]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_int3 = np.random.randint(0, 10, (4, 3))
rand_int4 = np.random.randint(0, 10, (4, 3))

rand_int3, rand_int4

(array([[3, 4, 6],
        [6, 3, 6],
        [2, 5, 1],
        [9, 8, 4]]),
 array([[5, 3, 9],
        [6, 8, 6],
        [0, 0, 8],
        [8, 3, 8]]))

In [67]:
# Perform a dot product on the two newest arrays you created
rand_int3.dot(rand_int4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it? I can use Transpose or reshape one of the array.

In [68]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand_int3.dot(rand_int4.T)

array([[ 81,  86,  48,  84],
       [ 93,  96,  48, 105],
       [ 34,  58,   8,  39],
       [105, 142,  32, 128]])

Notice how performing a transpose allows the dot product to happen.

Why is this? Transpose works because the switches the axes of the array from (4, 3) to (3, 4)

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [69]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_int5 = np.random.randint(0, 10, (4, 3))
rand_int6 = np.random.randint(0, 10, (4, 3))

rand_int5, rand_int6

(array([[2, 6, 5],
        [7, 8, 4],
        [0, 2, 9],
        [7, 5, 7]]),
 array([[8, 3, 0],
        [0, 9, 3],
        [6, 1, 2],
        [0, 4, 0]]))

In [70]:
# Compare the two arrays with '>'
rand_int5 > rand_int6

array([[False,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`? It returns array of filled with False and True

In [71]:
# Compare the two arrays with '>='
rand_int5 >+ rand_int6

array([[False,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [72]:
# Find which elements of the first array are greater than 7
rand_int5 > 7

array([[False, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False]])

In [74]:
# Which parts of each array are equal? (try using '==')
rand_int5 == rand_int6

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [75]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_int5)

array([[2, 5, 6],
       [4, 7, 8],
       [0, 2, 9],
       [5, 7, 7]])

In [76]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_int5)

array([[0, 2, 1],
       [2, 0, 1],
       [0, 1, 2],
       [1, 0, 2]])

In [77]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_int5)

np.int64(8)

In [79]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_int5)

np.int64(6)

In [80]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_int5, axis=1)

array([1, 1, 2, 0])

In [81]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand_int5, axis=0)

array([2, 2, 1])

In [83]:
# Create an array of normally distributed random numbers
np.random.seed(0)
np.random.random((3, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [86]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.